project_id = "paper-radar"

[api]
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
