import type { Feed, FeedInput } from "@paper-radar/shared";

export const starterFeeds: FeedInput[] = [
  {
    name: "Theorem Proving & Lean",
    description: "Lean, proof assistants, and interactive theorem proving",
    include_keywords: "theorem proving, automated theorem proving, interactive theorem proving, formal proof, proof assistant, Lean, Lean 4, mathlib, dependent type theory, type theory, Coq, Isabelle, Agda",
    exclude_keywords: "tutorial, beginner, education",
    priority_keywords: "Lean, Lean 4, mathlib, theorem proving, proof assistant",
    min_semantic_similarity: 0.35,
    min_publication_year: 2018,
  },
  {
    name: "Automated Reasoning & Proof Search",
    description: "Algorithms for discovering proofs and solving logical problems",
    include_keywords: "proof search, premise selection, automated reasoning, proof synthesis, proof planning, SAT, SMT, first-order logic, higher-order logic, resolution, symbolic reasoning",
    exclude_keywords: "opinion, survey-only",
    priority_keywords: "proof search, premise selection, proof synthesis, automated reasoning",
    min_semantic_similarity: 0.4,
    min_publication_year: 2018,
  },
  {
    name: "Formal Methods & Verification",
    description: "Program verification, model checking, and software correctness",
    include_keywords: "formal methods, formal verification, program verification, model checking, static analysis, refinement types, Hoare logic, temporal logic, TLA+, software correctness",
    exclude_keywords: "tutorial, introductory, education",
    priority_keywords: "formal verification, program verification, model checking, software correctness",
    min_semantic_similarity: 0.4,
    min_publication_year: 2018,
  },
  {
    name: "AI for Mathematics & Proofs",
    description: "Machine learning and language models for mathematical reasoning",
    include_keywords: "neural theorem proving, LLM theorem proving, mathematical reasoning, proof generation, proof synthesis, large language models, language models, AI for mathematics, machine learning for code",
    exclude_keywords: "computer vision, image classification, speech recognition, robotics",
    priority_keywords: "neural theorem proving, proof generation, Lean, mathematical reasoning",
    min_semantic_similarity: 0.45,
    min_publication_year: 2020,
  },
  {
    name: "Type Theory & Programming Languages",
    description: "Type systems, semantics, and foundations of programming languages",
    include_keywords: "programming languages, type theory, dependent types, lambda calculus, operational semantics, denotational semantics, compiler verification, type systems, proof theory",
    exclude_keywords: "web development, database systems, networking",
    priority_keywords: "dependent types, type systems, lambda calculus, semantics",
    min_semantic_similarity: 0.4,
    min_publication_year: 2018,
  },
  {
    name: "Frontier ML & LLMs",
    description: "Cutting-edge machine learning research covering foundation models, large language models, reasoning systems, multimodal models, AI agents, generative modeling, reinforcement learning, robotics, and emerging training methods.",
    include_keywords: "foundation models, large language models, LLMs, generative AI, generative models, transformer, attention, scaling laws, pretraining, post-training, instruction tuning, RLHF, reinforcement learning, reasoning models, test-time compute, AI agents, agentic AI, tool use, multimodal learning, vision-language models, world models, diffusion models, flow matching, representation learning, self-supervised learning, synthetic data, embodied AI, robotics learning, machine learning systems",
    exclude_keywords: "medical diagnosis, finance, marketing, education",
    priority_keywords: "foundation models, scaling laws, reasoning models, AI agents",
    min_semantic_similarity: 0.45,
    min_publication_year: 2020,
  },
  {
    name: "Multimodal & Agentic ML",
    description: "Models that perceive, reason, and act across modalities and tools",
    include_keywords: "multimodal learning, vision-language models, vision-language-action, embodied AI, tool use, agentic AI, computer use, long-context models, world models, robotics learning",
    exclude_keywords: "medical imaging, autonomous driving, surveillance",
    priority_keywords: "multimodal learning, tool use, agentic AI, world models",
    min_semantic_similarity: 0.45,
    min_publication_year: 2020,
  },
  {
    name: "Generative Models & Representation Learning",
    description: "Generative modeling, self-supervised learning, and learned representations",
    include_keywords: "generative models, diffusion models, flow matching, self-supervised learning, representation learning, contrastive learning, energy-based models, variational inference, synthetic data, generative modeling",
    exclude_keywords: "image editing, marketing, advertising",
    priority_keywords: "diffusion models, flow matching, representation learning, self-supervised learning",
    min_semantic_similarity: 0.45,
    min_publication_year: 2018,
  },
  {
    name: "Mathematics, Probability & Statistics",
    description: "Combinatorics, number theory, analysis, graph theory, probability, randomness, statistical learning theory, and applied statistics",
    include_keywords: "combinatorics, extremal combinatorics, probabilistic combinatorics, additive combinatorics, graph theory, random graphs, number theory, analytic number theory, algebraic number theory, probability theory, random processes, stochastic processes, concentration inequalities, real analysis, harmonic analysis, functional analysis, statistical learning theory, learning theory, high-dimensional statistics, mathematical statistics, statistical inference, Bayesian statistics, causal inference, randomized algorithms",
    exclude_keywords: "tutorial, textbook, education, survey-only",
    priority_keywords: "combinatorics, number theory, graph theory, random graphs, probability theory, statistical learning theory, high-dimensional statistics, harmonic analysis",
    min_semantic_similarity: 0.4,
    min_publication_year: 2010,
  },
  {
    name: "Multi-Agent & Federated Learning",
    description: "Multi-agent systems, decentralized learning, federated learning, coordination, and privacy-preserving machine learning",
    include_keywords: "multi-agent reinforcement learning, multi-agent systems, decentralized learning, federated learning, federated optimization, distributed machine learning, collaborative learning, agent coordination, emergent communication, cooperative agents, competitive agents, swarm intelligence, privacy-preserving machine learning, differential privacy, split learning",
    exclude_keywords: "tutorial, textbook, education, survey-only",
    priority_keywords: "multi-agent reinforcement learning, federated learning, agent coordination, decentralized learning, federated optimization, emergent communication",
    min_semantic_similarity: 0.42,
    min_publication_year: 2018,
  },
  {
    name: "Machine Learning for Finance",
    description: "Machine learning research for financial markets, forecasting, risk, portfolio construction, and financial decision-making",
    include_keywords: "machine learning for finance, financial machine learning, quantitative finance, asset pricing, financial forecasting, return prediction, volatility forecasting, portfolio optimization, algorithmic trading, market microstructure, limit order books, credit risk, market risk, fraud detection, financial time series, fintech",
    exclude_keywords: "tutorial, textbook, education, survey-only, investment advice, cryptocurrency promotion",
    priority_keywords: "financial machine learning, financial forecasting, volatility forecasting, portfolio optimization, market microstructure, credit risk",
    min_semantic_similarity: 0.42,
    min_publication_year: 2018,
  },
];

export function uncreatedStarterFeeds(feeds: Pick<Feed, "name">[]) {
  const existing = new Set(feeds.map((feed) => feed.name?.trim().toLowerCase()).filter(Boolean));
  return starterFeeds.filter((feed) => !existing.has(feed.name.trim().toLowerCase()));
}
